highlighter: pygments
markdown: kramdown

title:            Assil Ksiksi
aboutme:          My name is Assil Ksiksi. I'm an Electrical Engineering student by day, and a programmer by night.
url:              https://www.prism.gatech.edu/~aksiksi3/
baseurl:          /~aksiksi3/
baseurl2:         /~aksiksi3

author:
  name:           Assil Ksiksi
  twitter:        https://twitter.com/aksiksi
  github:         https://github.com/aksiksi

paginate:         5
