highlighter: pygments
markdown: redcarpet

title:            'Assil Ksiksi'
tagline:          'Place for my thoughts'
# description:      ''
url:              http://assil.me
baseurl:          /

author:
  name:           'Assil Ksiksi'
  twitter:        https://twitter.com/Cyph0n
  github:         https://github.com/aksiksi
  cv:

paginate:         5

version:          0.2
