highlighter: pygments
markdown: redcarpet

title:            'A Blog'
tagline:          'Place for my thoughts'
# description:      ''
url:              http://cyph0n.github.io
baseurl:          /

author:
  name:           'Assil Ksiksi'
  twitter:        https://twitter.com/Cyph0n
  github:         https://github.com/Cyph0n
  cv:

paginate:         5

version:          0.1.0
