highlighter: rouge
markdown: kramdown

title:            Assil Ksiksi
aboutme:          My name is Assil Ksiksi. I write low-level software at Cisco.
url:              http://aksiksi.github.io/

author:
  name:           Assil Ksiksi
  twitter:        https://twitter.com/aksiksi
  github:         https://github.com/aksiksi

paginate:         10
