highlighter: rouge
markdown: kramdown

title:            Blog
aboutme:          My name is Assil and I'm a software enthusiast.
url:              https://assil.me

author:
  name:           Assil Ksiksi
  twitter:        https://twitter.com/aksiksi
  github:         https://github.com/aksiksi

paginate:         5
