plugins:
  - jekyll-paginate

highlighter: rouge
markdown: kramdown

title:            Assil Ksiksi
aboutme:          My name is Assil Ksiksi. I'm an Electrical Engineering student by day, and a programmer $
url:              https://assil.me/

author:
  name:           Assil Ksiksi
  twitter:        https://twitter.com/aksiksi
  github:         https://github.com/aksiksi

paginate:         5
